---
name: build esp-idf component

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
	build:
	runs-on: ubuntu-latest
	steps:
		- name: install esp-idf and build component
			uses: rmshub/esp-idf-action@v5
			with:
					esp_idf_version: v5.5
					esp_idf_target: esp32
